# Base
spring.application.name=testApp
# Swagger URI
springdoc.swagger-ui.path=/docs
# MongoDB Properties
spring.data.mongodb.uri=<MONGO_DB SERVER>
#spring.data.mongodb.host=<HOST>
#spring.data.mongodb.port=<PORT>
#spring.data.mongodb.database=journal_db
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.transaction=TRACE
# Weather API
spring.main.allow-circular-references=false
weather.api.key=<API_KEY>
weather.api.uri=<API_URI>
# Mail Server Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=<PORT>
spring.mail.username=<MAIL>
spring.mail.password=<PASSWORD>
# SMTP Properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Redis Properties
spring.data.redis.host=<REDIS_HOST>
spring.data.redis.port=<REDIS_PORT>
spring.data.redis.username=<REDIS_USERNAME>
spring.data.redis.password=<REDIS_PASS>
spring.data.redis.ssl.enabled=false
# Kafka bootstrap server (from Aiven console)
spring.kafka.bootstrap-servers=<AIVEN_URI>
# Consumer settings
spring.kafka.consumer.group-id=my-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# Producer settings
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
# SSL mTLS (Client Certificate Authentication)
spring.kafka.properties.security.protocol=SSL
spring.kafka.properties.ssl.endpoint.identification.algorithm=https
spring.kafka.properties.sasl.jaas.config=
spring.kafka.properties.sasl.mechanism=
spring.kafka.properties.ssl.truststore.location=classpath:client.truststore.jks
spring.kafka.properties.ssl.truststore.password=<PASSWORD>
spring.kafka.properties.ssl.truststore.type=JKS
spring.kafka.properties.ssl.keystore.location=classpath:client.keystore.p12
spring.kafka.properties.ssl.keystore.password=<PASSWORD>
spring.kafka.properties.ssl.keystore.type=PKCS12
# JWT
SECRET_KEY=<SECRET_KEY>
test=vYxIHIek+e2A3P8x3NDTZjAPRp7rYxYgVNQD+pnJjeQ=



